### ISSUE TITLE
Pagination limit

### ISSUE THREAD

**Issue by jcuenod** [m4riok/strawberry-django-extras#1]
Is it possible to set a limit to the size of the `limit`?

**Comment by m4riok** [comment]
Hi @jcuenod 

I am using the default offset limit pagination from [strawberry-graphql-django](https://strawberry-graphql.github.io/strawberry-graphql-django/) and just wrapping it's result. As far as I know this feature is not supported. 

You could make a tiny field extension to check the limit provided and throw an exception or even modify it. Take a look at the documentation on [field extensions](https://strawberry.rocks/docs/guides/field-extensions#field-extensions). It should be easy enough to implement. Just make sure you add it in the correct order so it runs prior to the  `with_total_count()` extension.

**Comment by jcuenod** [comment]
Thanks, I'll look into that option!

**Comment by jcuenod** [comment]
Fyi, this was successful. Thanks!

**Comment by m4riok** [comment]
Thanks for letting me know.
