### ISSUE TITLE
Required "install"

### ISSUE THREAD

**Issue by jcuenod** [m4riok/strawberry-django-extras#2]
When I import `with_total_count`, I am required to add `strawberry_django_extras.jwt.refresh_token.apps.RefreshTokenConfig` to my `INSTALLED_APPS` in `settings.py`.

If all I'm using is pagination, I shouldn't need JWT refresh stuff.

**Comment by m4riok** [comment]
This shouldn't be the case. Could you provide the output of the exception you get if you do not add `strawberry_django_extras.jwt.refresh_token.apps.RefreshTokenConfig` to your `INSTALLED_APPS`. ?

**Comment by m4riok** [comment]
Hi @jcuenod 

Drafted a new release that should solve this issue. Closing this for now. If the problem is not resolved in v0.1.5 feel free to reopen the issue.

**Comment by jcuenod** [comment]
Thanks, this appears to have resolved the issue.
