### ISSUE TITLE
through default type

### ISSUE THREAD

**Issue by stygmate** [m4riok/strawberry-django-extras#5]
Hi,

is there a way to types through defaults instead of just using JSON ?

**Comment by m4riok** [comment]
Hi @stygmate,

Django itself handles through_defaults as a dict so no. If you need to have strong typing in you application you can always expose the intermediate table that holds the foreign keys and data through your schema and then it will be typed.

**Comment by m4riok** [comment]
Hi @stygmate , 

Another option is to subclass my `CRUDManyToManyItem` and  `CRUDManyToManyCreateInput` and add your specific values with types and use the __init__ of the subclass to populate through_defaults with these values. Here's an example:

**Models:** 

```python

class Person(models.Model):
    name = models.CharField(max_length=128)

    def __str__(self):
        return self.name


class Role(models.Model):
    name = models.CharField(max_length=128)
    members = models.ManyToManyField(Person, through="Membership",related_name="roles")

    def __str__(self):
        return self.name


class Membership(models.Model):
    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    role = models.ForeignKey(Role, on_delete=models.CASCADE)
    invite_reason = models.CharField(max_length=64)
```

Inputs: 
```python
T_CREATE = TypeVar('T_CREATE')

@strawberry.input
class MyCRUDManyToManyItem(CRUDManyToManyItem[T_CREATE],Generic[T_CREATE]):
    invite_reason: Optional[str] = UNSET

    def __init__(self, object_data: T_CREATE, through_defaults: Optional[JSON] = UNSET, invite_reason: Optional[str] = UNSET):
        self.object_data = object_data
        if through_defaults is UNSET:
            through_defaults = {}
        if invite_reason is not UNSET:
            through_defaults["invite_reason"] = invite_reason
        self.through_defaults = through_defaults


@strawberry.input
class MyCRUDManyToManyCreateInput(CRUDManyToManyCreateInput[T_CREATE], Generic[T_CREATE]):
    create: Optional[List[MyCRUDManyToManyItem[T_CREATE]]] = UNSET

@strawberry_django.input(Person)
class PersonInput:
    name: auto
    roles: Optional[MyCRUDManyToManyCreateInput[RoleInput]] = UNSET
```

Please do let me know if either of these suggestions are sufficient for your use case. Thanks.

**Comment by stygmate** [comment]
Hi, thank you for your response :) I finally decided to patch your library to include a new TypeVar (for through types) to your input types.

**Comment by m4riok** [comment]
Do you mean that you will change the way the relationship is saved to the database to not use Django's through_defaults ? Or do it like the example I posted and just introduce a dynamic way of specifying the types of through_defaults to be later populated in the dict ? I am curious because doing it in the second manner it's only truly strongly typed for the client that is consuming the API. As far as Django is concerned it is still just a dict.
